name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: site
          path: build
  build-functions:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm --prefix functions install
      - name: Build
        run: npm --prefix functions run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: functions
          path: functions/lib/
  deploy:
    name: Deploy
    needs: [build-site, build-functions]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Site Artifact
        uses: actions/download-artifact@master
        with:
          name: site
      - name: Download Functions Artifact
        uses: actions/download-artifact@master
        with:
          name: functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
